import type { Component } from 'vue'

import {
  CloudOutline,
  FolderOpenOutline,
  HomeOutline,
  SettingsOutline,
  SpeedometerOutline,
  AnalyticsOutline,
  DocumentTextOutline,
  InformationCircleOutline,
  ServerOutline,
  TvOutline,
  ShieldCheckmarkOutline,
  CopyOutline,
  PlayOutline,
  LinkOutline,
  NotificationsOutline,
  WarningOutline,
  KeyOutline,
  PeopleOutline,
  LibraryOutline,
  SearchOutline,
  StatsChartOutline,
  TimeOutline,
  SaveOutline,
  SwapHorizontalOutline,
  ConstructOutline,
  PulseOutline,
  GlobeOutline,
  FilmOutline,
  GitNetworkOutline,
  GridOutline,
  LayersOutline,
  ReturnDownBackOutline,
  PlayCircleOutline,
} from '@vicons/ionicons5'
import { PathMappingIcon } from '@/icons/PathMappingIcon'

export type IconComponent = Component

export const AppIcons = {
  overview: HomeOutline,
  home: HomeOutline,
  config: SettingsOutline,
  server: ServerOutline,
  emby: TvOutline,
  observability: AnalyticsOutline,
  s3: CloudOutline,
  backends: LinkOutline,
  s3Browser: FolderOpenOutline,
  cache: SpeedometerOutline,
  license: KeyOutline,
  security: ShieldCheckmarkOutline,
  notify: NotificationsOutline,
  alerts: WarningOutline,
  strm: DocumentTextOutline,
  docs: InformationCircleOutline,
  copy: CopyOutline,
  pathMapping: PathMappingIcon,
  play: PlayOutline,
  users: PeopleOutline,
  library: LibraryOutline,
  search: SearchOutline,
  stats: StatsChartOutline,
  activity: TimeOutline,
  logs: DocumentTextOutline,
  backup: SaveOutline,
  migrate: SwapHorizontalOutline,
  settings: SettingsOutline,
  metadata: DocumentTextOutline,
  apikeys: KeyOutline,
  webhook: NotificationsOutline,
  tools: ConstructOutline,

  // Section-level icons (一级模块图标)
  media: FilmOutline,
  gateway: GitNetworkOutline,
  system: ConstructOutline,

  // Observability sub-items (观测中心二级菜单图标)
  traffic: PulseOutline,
  redirect: ReturnDownBackOutline,
  ipStats: GlobeOutline,
  playback: PlayCircleOutline,

  // Misc extras
  dashboard: GridOutline,
  layers: LayersOutline,
} as const
